### ISSUE TITLE
support different environments

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/project_greeter_bot#33]
would like to be able to run in test and production modes - something like this:

```js
if process.env.ENV == 'production'
  const greetings = { 
                    'C0KK907B5': ls_greet, 
                    'C029E8G80': wso_greet, 
                    'C5LCQSJMA': rfm_greet, 
                    'C724RCXT7': wed_greet,
                    'C0VEPAPJP': metplus_greet,
                    'C3ETFTYHK': bot_greet, 
                    'C2HGJF54G': async_greet
                  };
else
  const greetings = { 
    'CDLLCBT4Z': ls_greet, 
    'CDM8RJUBU': wso_greet, 
    'CDLLCJJGH': rfm_greet, 
    'CDM5X3TFV': wed_greet,
    'CDNAU3CCB': metplus_greet,
    'CDNDNJPHQ': bot_greet,
    'CDMRA0DS5': async_greet
  };
```

then run via: ```ENV=PRODUCTION npm start```

**Comment by tansaku** [comment]
could also use https://www.npmjs.com/package/dotenv

**Comment by tansaku** [comment]
or maybe:

```js
let greetings

if (process.env.ENV === 'production') {

  // slack channel ids for main AV slack
  greetings = {
    'C0KK907B5': ls_greet,
    'C029E8G80': wso_greet,
    'C5LCQSJMA': rfm_greet,
    'C724RCXT7': wed_greet,
    'C0VEPAPJP': metplus_greet,
    'C3ETFTYHK': bot_greet,
    'C2HGJF54G': async_greet
  };
} else {

  // slack channel ids for bottest slack

  greetings = {
    'CDLLCBT4Z': ls_greet,
    'CDM8RJUBU': wso_greet,
    'CDLLCJJGH': rfm_greet,
    'CDM5X3TFV': wed_greet,
    'CDNAU3CCB': metplus_greet,
    'CDNDNJPHQ': bot_greet,
    'CDMRA0DS5': async_greet
  };
}
```

**Comment by HackermanArjun** [comment]
Where is the .env file?
You will need it

**Comment by tansaku** [comment]
you have to create it if you want it - like this:

![](https://dl.dropbox.com/s/mot99m17fmi6isp/Screenshot%202018-11-16%2012.36.26.png?dl=0)

**Comment by tansaku** [comment]
you don't have to have it, you can alternatively just run like so:

```
ENV=development npm start
```

**Comment by HackermanArjun** [comment]
You said that we need that exact token??? The keys don't matter at all if you don't use the right token.
The command with the token:

`PROJECT_GREETER_SLACK_BOT_TOKEN=xxxx npm start`

Which is why it will be necessary to create a .env file

Or maybe we don't need a token for production mode?

**Comment by tansaku** [comment]
Hi @HackermanArjun please don't post the token in github or it may be auto-expired.

And yes, we need the exact token.  The keys (channel ids) don't matter if you are not using the right token, but still we want all developers to be testing on agileventuresbottest.slack.com  not on agileventures.slack.com - we don't hand out the token for the latter

However, both tokens shouldn't be put into git or github.

Think through what we had to do to get it working for you:

1. run with the correct token
2. adjust greetings.js with the correct ids
3. go to agilventuresbottest.slack.com

So with this latest change we are trying to remove step 2.  Anyone starting to work on this from scratch will need to still get the token (i.e. step 1), but that's normal.

The token could be placed in .env, but if we do we want to make sure that it is NOT checked in to git or github ...

**Comment by tansaku** [comment]
@HackermanArjun perhaps reading https://medium.com/ibm-watson-data-lab/environment-variables-or-keeping-your-secrets-secret-in-a-node-js-app-99019dfff716 might be helpful?

**Comment by justinemar** [comment]
I am working on this
