### ISSUE TITLE
easier in ruby?

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/project_greeter_bot#6]
would all this be easier in ruby (the testing part?) less asynchronous stuff to worry about, but then again, is node much lighter weight and will cost less to run on the server?

**Comment by HackermanArjun** [comment]
Node JS is a very efficient and light language. Even easier to code for most as they are web developers and they know JavaScript so node would be easy for them.

**Comment by HackermanArjun** [comment]
I think this issue should be closed.
